version: '3'
services:
  tor1:
    image: torserver:latest

  tor2:
    image: torserver:latest

  tor3:
    image: torserver:latest

  tor4:
    image: torserver:latest

  tor5:
    image: torserver:latest

  tor6:
    image: torserver:latest

  tor7:
    image: torserver:latest

  tor8:
    image: torserver:latest

  tor9:
    image: torserver:latest

  tor10:
    image: torserver:latest

  proxy:
    image: nginx:latest
    ports:
      - "0.0.0.0:19050:9050"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
